"""
Blender scene creation script template.
This file is generated by the BlenderRenderEngine and executed inside Blender.
"""

import bpy
import json
import os
import sys
from pathlib import Path

def setup_scene(settings):
    """Set up the Blender scene based on provided settings."""
    # Clear existing objects using data API (safer in headless)
    for obj in bpy.data.objects:
        bpy.data.objects.remove(obj, do_unlink=True)
    
    # Ensure we have a valid scene
    if not bpy.context.scene:
        bpy.ops.scene.new(type='EMPTY')
    scene = bpy.context.scene
    
    # Basic scene settings
    scene.render.resolution_x = settings.get('resolution_x', 1920)
    scene.render.resolution_y = settings.get('resolution_y', 1080)
    scene.render.fps = settings.get('fps', 30)
    scene.frame_start = 1
    scene.frame_end = settings.get('frame_count', 60)
    
    # Configure output
    output_dir = Path(settings.get('output_dir', '.'))
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = str(output_dir / 'output')
    
    scene.render.filepath = output_path
    scene.render.image_settings.file_format = 'FFMPEG'
    scene.render.ffmpeg.format = 'MPEG4'
    scene.render.ffmpeg.codec = 'H264'
    
    # Create a simple scene using data API
    mesh = bpy.data.meshes.new('Cube')
    obj = bpy.data.objects.new('Cube', mesh)
    scene.collection.objects.link(obj)
    
    # Add camera
    cam_data = bpy.data.cameras.new('Camera')
    cam_obj = bpy.data.objects.new('Camera', cam_data)
    cam_obj.location = (0, -5, 2)
    cam_obj.rotation_euler = (1.0, 0, 0)
    scene.collection.objects.link(cam_obj)
    scene.camera = cam_obj
    
    # Add light
    light_data = bpy.data.lights.new('Light', 'SUN')
    light_obj = bpy.data.objects.new('Light', light_data)
    light_obj.location = (5, 5, 10)
    light_data.energy = 1.5
    scene.collection.objects.link(light_obj)
    
    return scene

def main():
    if '--' not in sys.argv:
        print("Error: No arguments provided", file=sys.stderr)
        sys.exit(1)
        
    args = sys.argv[sys.argv.index('--') + 1:]
    if not args:
        print("Error: No settings file provided", file=sys.stderr)
        sys.exit(1)
        
    settings_path = Path(args[0])
    if not settings_path.exists():
        print(f"Error: Settings file not found: {settings_path}", file=sys.stderr)
        sys.exit(1)
        
    try:
        with open(settings_path, 'r') as f:
            settings = json.load(f)
            
        # Set up the scene
        scene = setup_scene(settings)
        output_path = scene.render.filepath
        
        # Save the .blend file if requested
        if 'blend_output' in settings:
            try:
                bpy.ops.wm.save_as_mainfile(filepath=str(settings['blend_output']))
                print(f"Saved scene to: {settings['blend_output']}")
            except Exception as e:
                print(f"Warning: Failed to save .blend file: {e}", file=sys.stderr)
            
        # Render if requested
        if settings.get('render', False):
            print("Starting render...")
            bpy.ops.render.render(animation=True)
            print(f"Render complete. Output: {output_path}")
            
        sys.exit(0)
        
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON in settings file: {settings_path}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {str(e)}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
